#!/bin/bash
# ulimit -c unlimited

# Binaries and data dirs
INSTDIR=`pwd`/tmp_install
QUERY_DIR=/home/alena/jo-bench/queries

# Set PG environment variables for correct access to the DBMS
export PGDATA=/home/alena/postgres_data
# export PGPORT=5432
export PGUSER=`postgres`

# Stop instances and clean logs.
 pg_ctl -D $PGDATA stop
 rm -rf logfile.log
# Kill all processes
 unamestr=`uname`
 if [[ "$unamestr" == 'Linux' ]]; then
     pkill -U `whoami` -9 -e postgres
 	pkill -U `whoami` -9 -e pgbench
	pkill -U `whoami` -9 -e psql
 elif [[ "$OSTYPE" == "darwin"* ]]; then
     killall -u `whoami` -vz -9 postgres
     killall -u `whoami` -vz -9 pgbench
     killall -u `whoami` -vz -9 psql
 else
     echo "Unintended OS."
 fi
 sleep 1

tmp_install/bin/psql postgres -c "create database alena"

# Set parameters
tmp_install/bin/psql -f /home/alena/postgrespro_new/jo-bench/schema.sql
tmp_install/bin/psql -f /home/alena/postgrespro_new/jo-bench/fkindexes.sql
tmp_install/bin/psql -vdatadir="'/home/alena/jo-bench'" -f /home/alena/jo-bench/copy.sql
